### ISSUE TITLE
QUESTION : How can I access socket io form server/api?

### ISSUE THREAD

**Issue by mandaputtra** [sush1lemon/nuxt-socket.io#1]
Is there a way to access socket io server instance from `server/api`folder?

**Comment by sush1lemon** [comment]
@mandaputtra I think you can pass it to the event using the nitro hook like this.

https://github.com/sush1lemon/nuxt-socket.io/commit/cc399b465bb72807b74ff0ca935a1966e24131c6
https://github.com/sush1lemon/nuxt-socket.io/commit/b547bd6a4108b34eae61e31aebef00e6b91fa77e

**Comment by daehyun-thevc** [comment]
Salute good work. I have one question, can you give me a reason as to why you need to put `io` in `args[1]['_socket']` when it is a request? the type of args is `[event: H3Event<EventHandlerRequest>]`. is it undefined when indexing args to 1? I would like to know the reference.

**Comment by daehyun-thevc** [comment]
@sush1lemon 
Salute good work. I have one question, can you give me a reason as to why you need to put `io` in `args[1]['_socket']` when it is a request? the type of args is `[event: H3Event<EventHandlerRequest>]`. is it undefined when indexing args to 1? I would like to know the reference.

**Comment by sush1lemon** [comment]
> @sush1lemon Salute good work. I have one question, can you give me a reason as to why you need to put `io` in `args[1]['_socket']` when it is a request ([cc399b4](https://github.com/sush1lemon/nuxt-socket.io/commit/cc399b465bb72807b74ff0ca935a1966e24131c6))? the type of args is `[event: H3Event<EventHandlerRequest>]`. is it undefined when indexing args to 1? I would like to know the reference.

@daehyun-thevc
When you console.log the ```event``` from the hook, you can see that the ```event.args``` is an array, index 0 is a string, and the index 1 is the ```H3Event```, I'm just ensuring that the ```event.args``` has the index 1 so it doesn't throw an error.

![image](https://github.com/sush1lemon/nuxt-socket.io/assets/37240199/4b2f5c80-1f13-46b9-aebd-3d3ea2396405)

**Comment by daehyun-thevc** [comment]
@sush1lemon 
Thank you so much for your quick response. I actually regretted asking the question after I posted it because I could have just taken a picture of the console. So I deleted it as soon as I saw the result, but I'm a little embarrassed that it was answered right away. Keep up the good work and thank you for your kind response. 👍👍👍👍

**Comment by sush1lemon** [comment]
@daehyun-thevc

No problem at all! Your question was perfectly fine, and I'm here to help, Btw you can use can replace the current hook to this to avoid the checking of arg,

```
nitroApp.hooks.hook("request", (event)  => {
  event["_socket"] = io
})
```

![image](https://github.com/sush1lemon/nuxt-socket.io/assets/37240199/3941bcd5-9517-4284-834a-6ab97f813a1f)

**Comment by daehyun-thevc** [comment]
@sush1lemon 

I was just wondering if using hooks.hooks would be a clearer way to go. Thanks for the advice!
