### ISSUE TITLE
"#internal/nitro/utils" & "#internal/nitro/shutdown" throw linting errors

### ISSUE THREAD

**Issue by BlackoutGG** [sush1lemon/nuxt-socket.io#2]
Both say neither module exists

**Comment by sush1lemon** [comment]
@BlackoutGG i added type for "#internal/nitro/utils" and "#internal/nitro/shutdown", see https://github.com/sush1lemon/nuxt-socket.io/commit/8acf88b05b4cbff2e3f05c7f0f1166d306af302a

**Comment by BlackoutGG** [comment]
> @BlackoutGG i added type for "#internal/nitro/utils" and "#internal/nitro/shutdown", see [8acf88b](https://github.com/sush1lemon/nuxt-socket.io/commit/8acf88b05b4cbff2e3f05c7f0f1166d306af302a)

Thank you.
