### ISSUE TITLE
Hot reloading not working

### ISSUE THREAD

**Issue by timstrasser** [sush1lemon/nuxt-socket.io#4]
I used this solution to get socket.io to work, and the socket.io part works fine.
However, I noticed, that as soon as I use the socket.client.ts plugin to connect to the socket server (using io()) hot reloading stops working after a page reload.

After that, changes made to my pages/components are only visible after I reload the entire page. I suspect, the nitro preset affecting the Nuxt internal websocket server. Is this a known issue, or does it just happen for me?

Besides this, I ran into some other minor issues:
- I've noticed Nuxt restarting multiple times, because of file changes. However, I did not change these files.
- [unhandledRejection] write EPIPE 
- [unhandledRejection] read ECONNRESET

I'm on Nuxt 3.9.3. Is the solution suggested in this repo outdated, or it is something wrong on my end?

I basically copied the nitro presets, the plugin and for the handler, I just replace the event handlers with console logs.

**Comment by sush1lemon** [comment]
@timstrasser 
I suggest you copy the latest version of the [entry file](https://github.com/unjs/nitro/blob/main/src/runtime/entries/nitro-dev.ts) and add the socket part to it, you can see that the latest [entry file](https://github.com/unjs/nitro/blob/main/src/runtime/entries/nitro-dev.ts) is very different from this [old entry file](https://github.com/sush1lemon/nuxt-socket.io/blob/main/preset/entry.dev.ts)

**Comment by timstrasser** [comment]
Thank you for your quick answer!

I looked at the new entry file, however this latest version is not yet in a release of nitro.

Nuxt 3.9.3 (and also nuxt-nightly@latest) use nitro version 2.8.1, there the [entry file](https://github.com/unjs/nitro/blob/b53e00191d0752c7ae7463a907f0858c8bb8182e/src/runtime/entries/nitro-dev.ts) doesn't seem to differ much from what is in this repo.

I copied the current entry file from the nitro repo, made the changes, but the problem with hot reloading (and the others too) still persists.

**Comment by sush1lemon** [comment]
@timstrasser 

After testing it locally, i found that the socket.client.ts plugin is the one causing the issue, removing it resolve the issue, replaced it with just a .ts file that contains. (I didn't change the preset)

```
import { io } from 'socket.io-client';

export const useSocket = () => {
  return io();
};
```

**Comment by timstrasser** [comment]
I can confirm, this does resolve the issue. Thank you very much!

Will this repository be updated with a more sophisticated solution, or is this already a good solution?

For my app this solution works as is, but I see it causing problems if io is required in multiple places (as it calls makes a new connection each time).

A minimal nuxt + socket.io starter repo would be great, how sure if you're interested in creating one. I sure hope there will be a propper socket.io plugin for Nuxt 3 one day...

**Comment by sush1lemon** [comment]
I think we don't need a more sophisticated solution. This project is just a workaround while we are waiting for the official support for ws/socket.io from nuxt team


Btw, you can still use the socket.client plugin but you need to set the socket.io **transport to polling** on dev. I think that this is the main issue why does the hmr breaks. [updated entry.dev file](https://github.com/sush1lemon/nuxt-socket.io/blob/d290f41b11a6024b864ad90fb4ec1baca560799e/preset/entry.dev.ts#L47)

**Comment by timstrasser** [comment]
Yes, I see. Thank you very much for your help. This workaround should be alright for the time being, as long as the nitro entry files don't change too much.
